# Generated by Django 5.1.1 on 2024-11-11 21:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listado_publicaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anunciomunicipal',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='evidencia',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='fecha_publicacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='respuestamunicipal',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
