# Generated by Django 5.1.1 on 2024-11-25 22:01

import cloudinary.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listado_publicaciones', '0002_alter_anunciomunicipal_fecha_alter_evidencia_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anunciomunicipal',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='listado_publicaciones.categoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anunciomunicipal',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=100),
        ),
        migrations.AddField(
            model_name='anunciomunicipal',
            name='subtitulo',
            field=models.CharField(default='A', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ImagenAnuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagen')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('extension', models.CharField(max_length=30)),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='listado_publicaciones.anunciomunicipal')),
            ],
        ),
    ]
