# Generated by Django 5.1.1 on 2024-11-26 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listado_publicaciones', '0004_alter_anunciomunicipal_subtitulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencia',
            name='publicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listado_publicaciones.publicacion'),
        ),
        migrations.AlterField(
            model_name='imagenanuncio',
            name='anuncio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listado_publicaciones.anunciomunicipal'),
        ),
    ]
