# Generated by Django 5.1.1 on 2024-12-01 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listado_publicaciones', '0005_alter_evidencia_publicacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='juntavecinal',
            name='nombre_junta',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='codigo',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='nombre_calle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='numero_calle',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='juntavecinal',
            name='nombre_calle',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
