# Generated by Django 5.1.1 on 2024-12-10 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listado_publicaciones', '0006_juntavecinal_nombre_junta_publicacion_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='situacion',
            field=models.ForeignKey(blank=True, default=4, null=True, on_delete=django.db.models.deletion.RESTRICT, to='listado_publicaciones.situacionpublicacion'),
        ),
    ]
