# Generated by Django 5.1.1 on 2025-08-17 21:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listado_publicaciones', '0008_remove_publicacion_nombre_calle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20),
        ),
        migrations.AddField(
            model_name='categoria',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='departamentomunicipal',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20),
        ),
        migrations.AddField(
            model_name='departamentomunicipal',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='departamentomunicipal',
            name='jefe_departamento',
            field=models.OneToOneField(blank=True, limit_choices_to={'tipo_usuario': 'jefe_departamento'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departamento_dirigido', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='juntavecinal',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20),
        ),
        migrations.AddField(
            model_name='juntavecinal',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='prioridad',
            field=models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('vecino', 'Vecino'), ('personal', 'Personal Municipal'), ('jefe_departamento', 'Jefe de Departamento'), ('administrador', 'Administrador Municipal')], default='vecino', max_length=20),
        ),
        migrations.CreateModel(
            name='HistorialModificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('campo_modificado', models.CharField(max_length=100)),
                ('valor_anterior', models.TextField()),
                ('valor_nuevo', models.TextField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listado_publicaciones.publicacion')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioDepartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_fin_asignacion', models.DateTimeField(blank=True, null=True)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios', to='listado_publicaciones.departamentomunicipal')),
                ('usuario', models.ForeignKey(limit_choices_to={'esta_activo': True, 'tipo_usuario__in': ['personal', 'jefe_departamento']}, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_departamento', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asignación Usuario-Departamento',
                'verbose_name_plural': 'Asignaciones Usuario-Departamento',
                'unique_together': {('usuario', 'departamento')},
            },
        ),
    ]
