# Generated by Django 5.1.1 on 2025-08-17 22:45

import cloudinary.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listado_publicaciones', '0009_categoria_estado_categoria_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestamunicipal',
            name='puntuacion',
            field=models.IntegerField(choices=[(1, '1 estrella'), (2, '2 estrellas'), (3, '3 estrellas'), (4, '4 estrellas'), (5, '5 estrellas')], default=0, help_text='Puntuación del 1 al 5'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ultimo_acceso',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='estado',
            field=models.CharField(choices=[('habilitado', 'Habilitado'), ('pendiente', 'Pendiente'), ('deshabilitado', 'Deshabilitado')], default='habilitado', max_length=20),
        ),
        migrations.AlterField(
            model_name='departamentomunicipal',
            name='estado',
            field=models.CharField(choices=[('habilitado', 'Habilitado'), ('pendiente', 'Pendiente'), ('deshabilitado', 'Deshabilitado')], default='habilitado', max_length=20),
        ),
        migrations.AlterField(
            model_name='juntavecinal',
            name='estado',
            field=models.CharField(choices=[('habilitado', 'Habilitado'), ('pendiente', 'Pendiente'), ('deshabilitado', 'Deshabilitado')], default='habilitado', max_length=20),
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('accion', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('modulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('es_exitoso', models.BooleanField(default=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Columna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('limite_tareas', models.PositiveIntegerField(default=0)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='listado_publicaciones.departamentomunicipal')),
            ],
        ),
        migrations.CreateModel(
            name='EvidenciaRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', cloudinary.models.CloudinaryField(max_length=255, verbose_name='archivo')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('extension', models.CharField(max_length=30)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('respuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='listado_publicaciones.respuestamunicipal')),
            ],
        ),
        migrations.CreateModel(
            name='Tablero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('columnas', models.ManyToManyField(related_name='tableros', to='listado_publicaciones.columna')),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_limite', models.DateTimeField(blank=True, null=True)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], max_length=50)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='listado_publicaciones.categoria')),
                ('columna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='listado_publicaciones.columna')),
                ('encargado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('publicaciones', models.ManyToManyField(blank=True, related_name='tareas_asociadas', to='listado_publicaciones.publicacion')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listado_publicaciones.tarea')),
            ],
        ),
    ]
