# Generated by Django 5.1.1 on 2025-08-18 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listado_publicaciones', '0010_respuestamunicipal_puntuacion_usuario_ultimo_acceso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='columna',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='tablero',
            name='columnas',
        ),
        migrations.RemoveField(
            model_name='usuariodepartamento',
            name='cargo',
        ),
        migrations.AddField(
            model_name='columna',
            name='tablero',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='columnas', to='listado_publicaciones.tablero'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tablero',
            name='departamento',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.RESTRICT, related_name='tableros', to='listado_publicaciones.departamentomunicipal'),
            preserve_default=False,
        ),
    ]
