# Generated by Django 5.1.1 on 2025-08-19 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listado_publicaciones', '0011_remove_columna_departamento_remove_tablero_columnas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juntavecinal',
            name='comuna',
        ),
        migrations.RemoveField(
            model_name='juntavecinal',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='juntavecinal',
            name='villa',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='encargado',
            field=models.ForeignKey(blank=True, limit_choices_to={'es_municipal': True}, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='publicaciones_encargadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
