# Generated by Django 5.1.1 on 2025-08-19 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listado_publicaciones', '0012_remove_juntavecinal_comuna_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='es_incognito',
            field=models.BooleanField(default=False),
        ),
    ]
