# Generated by Django 5.1.1 on 2025-08-19 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listado_publicaciones', '0013_publicacion_es_incognito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='encargado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='publicaciones_encargadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
