# Generated by Django 5.1.1 on 2025-10-20 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listado_publicaciones', '0014_alter_publicacion_encargado'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencia',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='peso',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evidenciarespuesta',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='evidenciarespuesta',
            name='peso',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
