# Generated by Django 5.1.1 on 2025-10-20 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listado_publicaciones', '0015_evidencia_nombre_evidencia_peso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenanuncio',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='imagenanuncio',
            name='peso',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
