# Generated by Django 5.1.1 on 2025-10-27 20:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listado_publicaciones', '0016_imagenanuncio_nombre_imagenanuncio_peso'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispositivoNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_expo', models.CharField(help_text='Token de Expo para notificaciones push', max_length=255, unique=True)),
                ('plataforma', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android')], help_text='Plataforma del dispositivo (iOS, Android)', max_length=50)),
                ('activo', models.BooleanField(default=True, help_text='Indica si el dispositivo está activo para notificaciones')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha de registro del dispositivo')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, help_text='Última actualización del dispositivo')),
                ('usuario', models.ForeignKey(help_text='Usuario al que pertenece el dispositivo', on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos_notificacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dispositivo de Notificación',
                'verbose_name_plural': 'Dispositivos de Notificación',
                'db_table': 'dispositivos_notificacion',
                'ordering': ['-ultima_actualizacion'],
                'indexes': [models.Index(fields=['usuario', 'activo'], name='idx_usuario_activo'), models.Index(fields=['token_expo'], name='idx_token_expo')],
                'unique_together': {('usuario', 'token_expo')},
            },
        ),
    ]
