# Generated by Django 5.1.1 on 2025-10-27 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listado_publicaciones', '0017_dispositivonotificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialmodificaciones',
            name='publicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historialmodificaciones', to='listado_publicaciones.publicacion'),
        ),
    ]
